In [1]:
import pandas as pd
path = "recommender-system-2022-challenge-polimi-data/interactions_and_impressions.csv"

Interactions_and_Impressions = pd.read_csv(filepath_or_buffer=path,
                                           sep=",",
                                           header=1,
                                           engine='python',
                                           names=['UserId', 'ItemId', 'ImpressionList', 'Data'])
Interactions_and_Impressions

UserId  ItemId                 ImpressionList  Data
0             0      21                            NaN     0
1             0      21                            NaN     0
2             0      21  20,21,22,23,24,25,26,27,28,29     0
3             0      21                            NaN     1
4             0      21                            NaN     1
...         ...     ...                            ...   ...
5826500   41628   20448                            NaN     0
5826501   41628   20896                            NaN     1
5826502   41628   21506                            NaN     1
5826503   41628   22882                            NaN     0
5826504   41628   23757                            NaN     0

[5826505 rows x 4 columns]

In [2]:
Distinct_Interactions_no_mapping = Interactions_and_Impressions.copy(deep=True)
Distinct_Interactions_no_mapping = Distinct_Interactions_no_mapping.drop(["ImpressionList"], axis=1)
Distinct_Interactions_no_mapping

UserId  ItemId  Data
0             0      21     0
1             0      21     0
2             0      21     0
3             0      21     1
4             0      21     1
...         ...     ...   ...
5826500   41628   20448     0
5826501   41628   20896     1
5826502   41628   21506     1
5826503   41628   22882     0
5826504   41628   23757     0

[5826505 rows x 3 columns]

In [3]:
Distinct_Interactions_no_mapping = Distinct_Interactions_no_mapping.drop(["Data"], axis=1).drop_duplicates()
Distinct_Interactions_no_mapping['Rating'] = 1
Distinct_Interactions_no_mapping

UserId  ItemId  Rating
0             0      21       1
12            0      22       1
27            0      24       1
28            0      44       1
29            0      54       1
...         ...     ...     ...
5826500   41628   20448       1
5826501   41628   20896       1
5826502   41628   21506       1
5826503   41628   22882       1
5826504   41628   23757       1

[1554639 rows x 3 columns]

In [4]:
import scipy.sparse as sps

num_users = len(Distinct_Interactions_no_mapping.UserId.unique())
num_items = len(Distinct_Interactions_no_mapping.ItemId.unique())

urm_no_mapping = sps.csr_matrix((Distinct_Interactions_no_mapping.Rating, (Distinct_Interactions_no_mapping.UserId, Distinct_Interactions_no_mapping.ItemId)),
                                shape = (num_users, num_items))

In [5]:
import numpy as np
profile_length = np.ediff1d(urm_no_mapping.indptr)
profile_length, profile_length.shape

(array([ 65,  21, 103, ...,  23,  53,  23], dtype=int32), (41629,))

In [10]:
sorted_users = np.argsort(profile_length)
sorted_profiles = np.sort(profile_length)
sorted_users, sorted_profiles[:80]

(array([38400, 30257, 25061, ..., 19407,  8693, 12454]),
 array([ 5,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10], dtype=int32))

## Let's look at a submission

In [11]:
path = "submissions/slim_whole_dataset.csv.csv"

Submission = pd.read_csv(filepath_or_buffer=path,
                                           sep=",",
                                           header=1,
                                           engine='python',
                                           names=['UserId', 'Recs'])
Submission

UserId                                               Recs
0           1           6874 1068 56 62 393 665 124 13988 270 61
1           2   121 7864 8819 21319 925 453 1311 6712 1308 18939
2           3           20 917 269 58 557 393 22752 1911 352 174
3           4                 23 80 68 124 541 64 436 21 2119 56
4           5              53 25 21 348 393 124 888 468 2694 596
...       ...                                                ...
41110   41624  22403 11552 617 752 10221 7864 1024 15054 1347...
41111   41625               53 23 393 56 598 909 1449 60 268 396
41112   41626            21 270 12118 61 22619 387 598 126 55 23
41113   41627    1214 4577 1754 1859 71 1561 5069 1558 19705 676
41114   41628          769 771 1022 2904 3596 21 22 763 929 6967

[41115 rows x 2 columns]

In [30]:
Submission[Submission["UserId"]==30257]

UserId                                 Recs
29912   30257  71 80 2106 67 2114 2111 63 84 75 68